CREATE TABLE IF NOT EXISTS app_role (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(100) NOT NULL,
    name varchar(100) NOT NULL,
    description text NULL,
    created_by varchar(50) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by varchar(50) NULL,
    updated_at timestamp NULL,
    CONSTRAINT app_role_pkey PRIMARY KEY (id),
    CONSTRAINT app_role_name_key UNIQUE (name),
    CONSTRAINT app_role_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT app_role_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES app_user(id)
);