CREATE TABLE IF NOT EXISTS app_menu_permission (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_id int4 NOT NULL,
    code VARCHAR(50) NOT NULL,
    action_name varchar(50) NOT NULL, 
    created_by varchar(50) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by varchar(50) NULL,
    updated_at timestamp NULL,
    CONSTRAINT app_menu_permission_pkey PRIMARY KEY (id),
    CONSTRAINT app_menu_permission_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES app_menu(id) ON DELETE CASCADE,
    CONSTRAINT app_menu_permission_menu_action_key UNIQUE (menu_id, action_name, code),
    CONSTRAINT app_menu_permission_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT app_menu_permission_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES app_user(id)
);