services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend-template
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./.env:/app/.env
      - ./database/migrations:/app/database/migrations
      - ./database/seeders:/app/database/seeders
      - ./scripts:/app/scripts
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - go-backend-template-network

  postgres:
    image: postgres:18
    container_name: go-backend-template-postgres
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_SCHEMA}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - go-backend-template-network

volumes:
  postgres_data:

networks:
  go-backend-template-network:
    name: go-backend-template-network
    driver: bridge
    attachable: true
