CREATE TABLE IF NOT EXISTS app_login (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id varchar(50) NULL,
	access_token text NULL,
	status varchar(10) NULL,
	ip_address varchar(100) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"type" varchar(10) DEFAULT 'web'::character varying NULL,
	CONSTRAINT app_login_pkey PRIMARY KEY (id),
	CONSTRAINT app_login_status_check CHECK (((status)::text = ANY ((ARRAY['login'::character varying, 'logout'::character varying])::text[]))),
	CONSTRAINT app_login_type_check CHECK (((type)::text = ANY ((ARRAY['api'::character varying, 'web'::character varying])::text[]))),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);