// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with email and password, returning tokens and user data. This endpoint uses a centralized error handler.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_auth_presenter.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_auth_presenter.SessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (e.g., Validation Error, Invalid JSON)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (e.g., Wrong email or password)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (e.g., Database connection issue)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logs out the current user by invalidating their session/token. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User Logout",
                "responses": {
                    "200": {
                        "description": "Successfully logged out",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (e.g., Validation Error, Invalid JSON)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (e.g., Database connection issue)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the profile details of the currently authenticated user. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get Current User Profile",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user profile",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_auth_presenter.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized (Invalid or missing token)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "User profile not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus": {
            "get": {
                "description": "Retrieves a paginated and searchable list of all menus in the system.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get List of All Menus (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for name, description, or URL",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get menu list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.ReadMenuListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get list menu",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new menu item to the system. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Create Menu",
                "parameters": [
                    {
                        "description": "Menu data to create",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.CreateMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully create menu",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid JSON or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus/parent": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all root-level menus (menus without a parent), typically for use in a dropdown. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get Parent Menus",
                "responses": {
                    "200": {
                        "description": "Successfully get parent menu",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.MenuParent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get parent menu",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus/reorder": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the sort order of menus using drag-and-drop. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Update Menu Order (Reorder)",
                "parameters": [
                    {
                        "description": "New menu order",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.UpdateMenuOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update menu order",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid JSON or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus/sidebar": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the menu list specifically for the authenticated user, filtered by their 'read' permissions and formatted in a nested tree structure for the sidebar.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get User's Sidebar Menu",
                "responses": {
                    "200": {
                        "description": "Successfully get sidebar menu",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.ReadMenuListResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get sidebar menu",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus/{menu_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing menu item by its ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Update Menu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Menu data to update",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.UpdateMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update menu",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid Menu ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing menu item by its ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Update Menu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully delete menu",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid Menu ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus/{menu_id}/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a paginated and searchable list of permissions (e.g., read, create) for a specific menu ID. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu Permission"
                ],
                "summary": "Get Menu Permission List",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the Menu",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search term for action_name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (e.g., action_name ASC)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get menu permission list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.PaginatePayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.ReadMenuPermissionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid Menu ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (Menu ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (Query parsing or usecase failure)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new permission (e.g., 'read', 'create') to a specific menu by its ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu Permission"
                ],
                "summary": "Create Menu Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Permission data to create",
                        "name": "permission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.CreateMenuPermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully create menu permission",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid Menu ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/menus/{menu_id}/permissions/{menu_permission_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the details of a single menu permission by its unique ID. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu Permission"
                ],
                "summary": "Get Menu Permission Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Menu Permission ID",
                        "name": "menu_permission_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get menu permission detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.ReadMenuPermissionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (Permission ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing menu permission (e.g., 'code', 'action_name') by its unique ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu Permission"
                ],
                "summary": "Update Menu Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Menu Permission ID",
                        "name": "menu_permission_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Permission data to update",
                        "name": "permission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.UpdateMenuPermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update menu permission",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (Permission ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific permission from a menu by its unique permission ID. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu Permission"
                ],
                "summary": "Delete Menu Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "menu_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Menu Permission ID",
                        "name": "menu_permission_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully delete menu permission",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (Permission ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a paginated and searchable list of all roles. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get Roles List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for role name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (e.g., name ASC)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get roles",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.PaginatePayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.ReadRoleResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new role. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Create Role",
                "parameters": [
                    {
                        "description": "Role data to create",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.CreateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully create role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid JSON or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed create role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/roles/role-access/{role_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all menu permissions associated with a specific role. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Menu Permission"
                ],
                "summary": "Get Role Menu Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get role menu permission",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.PaginatePayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.RoleAccessResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid Role ID",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Role ID not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get role menu permission",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates menu permission assigned to a specific role. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Menu Permission"
                ],
                "summary": "Update Role Menu Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role menu permission payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.UpdateRoleAccessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update role menu permission",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Role ID or Menu Permission not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/roles/{role_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the details of a single role by its ID. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get Role Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get role detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.ReadRoleResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid Role ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (Role ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get role detail",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing role by its ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Update Role",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role data to update",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Role ID not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed update role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a role by its ID. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Delete Role",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully delete role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid Role ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (Missing Auth)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Role ID not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed delete role",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a paginated and searchable list of users in the system. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for name or email",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (e.g., name ASC)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get users",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.PaginatePayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/be-dashboard-nba_internal_presentation_user_presenter.ReadUserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Failed get users",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user with the provided details. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "User data to create",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_user_presenter.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully create user",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid JSON or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Role ID not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the profile details of the currently authenticated user. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get Current User Profile",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user profile",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_user_presenter.ReadUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized (Invalid or missing token)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "User profile not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's profile details by their ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "description": "User data to update",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_user_presenter.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update user",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the details of a single user by their ID. Requires Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get user detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_user_presenter.ReadUserDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid User ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (User ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's profile details by their ID. Requires Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User data to update",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_user_presenter.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update user",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid ID, Invalid JSON, or Validation Error)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "User ID not found",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user by their ID. Requires Bearer token. Users cannot delete themselves.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully delete user",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.DataPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid User ID)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Attempt to delete own account)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found (User ID not found)",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.ErrorPayload"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "be-dashboard-nba_internal_presentation_auth_presenter.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_auth_presenter.SessionResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_auth_presenter.UserResponse"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_auth_presenter.UserResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "img_name": {
                    "type": "string"
                },
                "img_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.CreateMenuPermissionRequest": {
            "type": "object",
            "required": [
                "action_name",
                "code"
            ],
            "properties": {
                "action_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.ReadMenuPermissionResponse": {
            "type": "object",
            "properties": {
                "action_name": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "menu_id": {
                    "type": "integer"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_menu-permission_presenter.UpdateMenuPermissionRequest": {
            "type": "object",
            "required": [
                "action_name",
                "code"
            ],
            "properties": {
                "action_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_presenter.CreateMenuRequest": {
            "type": "object",
            "required": [
                "active",
                "display",
                "group",
                "name",
                "url"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string",
                    "maxLength": 100
                },
                "display": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "icon": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "parent_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "url": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_presenter.MenuListItem": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.MenuListItem"
                    }
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_presenter.MenuParent": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_presenter.ReadMenuListResponse": {
            "type": "object",
            "properties": {
                "group_childs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/be-dashboard-nba_internal_presentation_menu_presenter.MenuListItem"
                    }
                },
                "group_name": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_presenter.UpdateMenuOrderRequest": {
            "type": "object",
            "required": [
                "group",
                "sorted_ids"
            ],
            "properties": {
                "group": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "sorted_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "be-dashboard-nba_internal_presentation_menu_presenter.UpdateMenuRequest": {
            "type": "object",
            "required": [
                "active",
                "display",
                "group",
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string",
                    "maxLength": 100
                },
                "display": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "icon": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "parent_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "url": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "be-dashboard-nba_internal_presentation_response.DataPayload": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_response.ErrorPayload": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_response.PaginatePayload": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "paginate": {
                    "$ref": "#/definitions/be-dashboard-nba_internal_presentation_response.paginatePayload"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_response.paginatePayload": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "number"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.Access": {
            "type": "object",
            "properties": {
                "access_id": {
                    "type": "integer"
                },
                "access_name": {
                    "type": "string"
                },
                "has_access": {
                    "type": "boolean"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.CreateRoleRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.ReadRoleResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.RoleAccessResponse": {
            "type": "object",
            "properties": {
                "accesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.Access"
                    }
                },
                "menu_id": {
                    "type": "integer"
                },
                "menu_name": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.UpdateRoleAccessItem": {
            "type": "object",
            "required": [
                "access_id",
                "has_access"
            ],
            "properties": {
                "access_id": {
                    "type": "integer"
                },
                "has_access": {
                    "type": "boolean"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.UpdateRoleAccessRequest": {
            "type": "object",
            "required": [
                "access_item"
            ],
            "properties": {
                "access_item": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/be-dashboard-nba_internal_presentation_role_presenter.UpdateRoleAccessItem"
                    }
                }
            }
        },
        "be-dashboard-nba_internal_presentation_role_presenter.UpdateRoleRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_user_presenter.CreateUserRequest": {
            "type": "object",
            "required": [
                "active",
                "email",
                "full_name",
                "name",
                "password",
                "role_id"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_user_presenter.ReadUserDetailResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_user_presenter.ReadUserResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "be-dashboard-nba_internal_presentation_user_presenter.UpdateUserRequest": {
            "type": "object",
            "required": [
                "active",
                "email",
                "full_name",
                "name",
                "role_id"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer {your token}\" into the field below.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Base APP Go",
	Description:      "Template API for Golang project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
